# ==============================================================================
#  inventory.ini
#  Danh sach may chu Ansible quan ly - dat tai /opt/ansible/inventory.ini
#  tren ha-prx01 (Control Node).
# ==============================================================================

[webservers]
web01 ansible_host=10.1.20.31
web02 ansible_host=10.1.20.32

[webservers:vars]
ansible_user=root
ansible_ssh_private_key_file=/root/.ssh/id_ed25519
